<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tgm_megamenu"
 *
 * Auto generated by Extension Builder 2016-06-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TgM MegaMenu',
	'description' => '',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'lvmobile' => '1.3.0-1.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);